### PR TITLE
Fix GTP Echo Response

### PR DESCRIPTION
**Pull request by gab-arrobo**
GTP Echo Response is malformed (UDP and IP) when the "Private Extension" IE is present. This PR fixes the issue

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by thakurajayL** [comment]
ok to test

**Comment by amarsri28** [comment]
Thanks @gab-arrobo  for reviewing.
@thakurajayL  feel free to add reviewers .

**Review by amarsri28 — APPROVED** [review]
approving.

**Comment by amolonf** [comment]
retest this please

**Comment by thakurajayL** [comment]
retest this please

**Comment by amolonf** [comment]
retest this please

**Comment by amolonf** [comment]
retest this please

**Comment by amolonf** [comment]
retest this please

**Comment by amolonf** [comment]
retest this please!!

**Comment by gab-arrobo** [comment]
retest this please

**Review by thakurajayL — APPROVED** [review]

**Pull request merged**
