### PR TITLE
Bumps go version to 1.21 (latest stable)

### PR DESCRIPTION
**Pull request by gatici**
This project currently uses Go 1.16 which is end of life. This PR bumps the go version to 1.21 which is the latest stable release. 

The update is accomplished by running following commands:
```
go mod edit -go=1.21
go mod tidy
```

Reference: https://tip.golang.org/doc/go1.21

### CODE REVIEW

**Comment by gab-arrobo** [comment]
@dependabot rebase

**Comment by gab-arrobo** [comment]
@gatici please address the conflicts. Thanks!

**Comment by gatici** [comment]
> @gatici please address the conflicts. Thanks!

Hi, Conflict is resolved. Thanks!

**Comment by gab-arrobo** [comment]
Hi @gatici, both `test-integration-bess-native` and `test-integration-up4-docker` are going to fail because of the GO version requested in the GHA. The patch below should fix the issue. If you would like, I can try to update your PR with the below changes.
```
diff --git a/.github/workflows/test-integration.yml b/.github/workflows/test-integration.yml
index 573ecb2..d5da8c9 100644
--- a/.github/workflows/test-integration.yml
+++ b/.github/workflows/test-integration.yml
@@ -15,7 +15,7 @@ jobs:
       - uses: actions/checkout@v4
       - uses: actions/setup-go@v4
         with:
-          go-version: '1.16'
+          go-version: '>=1.21'
       - name: Run integration tests for PFCP Agent & UP4
         run: |
             make test-up4-integration-docker || (docker logs pfcpiface; exit 1)
@@ -25,7 +25,7 @@ jobs:
       - uses: actions/checkout@v4
       - uses: actions/setup-go@v4
         with:
-          go-version: '1.16'
+          go-version: '>=1.21'
       - name: Run integration tests for PFCP Agent & UP4
         run: |
           make test-bess-integration-native
```
Also, it would be good to make the following update in this other GHA:
```
diff --git a/.github/workflows/golangci-lint.yml b/.github/workflows/golangci-lint.yml
index 67bb0dd..fb0cc5d 100644
--- a/.github/workflows/golangci-lint.yml
+++ b/.github/workflows/golangci-lint.yml
@@ -16,7 +16,7 @@ jobs:
     steps:
       - uses: actions/setup-go@v4
         with:
-          go-version: '>1.17'
+          go-version: '>=1.21'
       - uses: actions/checkout@v4
       - name: golangci-lint
         uses: golangci/golangci-lint-action@v3.6.0
```

**Review by gab-arrobo — APPROVED** [review]
+1

**Pull request merged**
