### PR TITLE
chore: bump pfcpsim to v1.0.1

### PR DESCRIPTION
**Pull request by gruyaume**
# Description

Bump the pfcpsim module to v1.0.1. There was a breaking change from 0.1.0 to 1.0.1 that many functions now require an additional `urrs` parameter that we set to nil here.

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by gruyaume** [comment]
It seems that integration tests are failing for an unrelated reason:
```
8805: bind: address already in use 
```

**Comment by gab-arrobo** [comment]
> It seems that integration tests are failing for an unrelated reason:
> 
> ```
> 8805: bind: address already in use 
> ```

I started seeing that issue when this PFCPSIM PR was merged: https://github.com/omec-project/pfcpsim/pull/69

**Comment by gab-arrobo** [comment]
Hi @gruyaume, FYI, in this branch (https://github.com/gab-arrobo/upf/tree/update-pfcpsim-dep), I addressed the issue with the `integration-tests-bess` test. I do not remember why I was not able to complete/address the `integration-tests-up4` test.

**Comment by gab-arrobo** [comment]
> Hi @gruyaume, FYI, in this branch (https://github.com/gab-arrobo/upf/tree/update-pfcpsim-dep), I addressed the issue with the `integration-tests-bess` test. I do not remember why I was not able to complete/address the `integration-tests-up4` test.

Here is a cleaner version of the changes I made: https://github.com/gab-arrobo/upf/tree/pfcpsim-update, where I integrated the changes I made several months ago with the latest updates in the master branch.

**Comment by gab-arrobo** [comment]
> Hi @gruyaume, FYI, in this branch (https://github.com/gab-arrobo/upf/tree/update-pfcpsim-dep), I addressed the issue with the `integration-tests-bess` test. I do not remember why I was not able to complete/address the `integration-tests-up4` test.

FYI, here are the details for the issue with the test: https://github.com/gab-arrobo/upf/actions/runs/10482118234

**Comment by gab-arrobo** [comment]
> > Hi @gruyaume, FYI, in this branch (https://github.com/gab-arrobo/upf/tree/update-pfcpsim-dep), I addressed the issue with the `integration-tests-bess` test. I do not remember why I was not able to complete/address the `integration-tests-up4` test.
> 
> FYI, here are the details for the issue with the test: https://github.com/gab-arrobo/upf/actions/runs/10482118234

@gruyaume, I was able to resolve the issues with the `integration-tests` and opened PR #847

**Pull request closed without merging**
