### PR TITLE
Supporting 'N' packet burst & resolving series of crash

### PR DESCRIPTION
**Pull request by amarsri28**
This patch will enable Larger Packet burst sizes . It resolves series of crashes observed while testing with Larger burst sizes.
Patch under testing.

### CODE REVIEW

**Comment by amarsri28** [comment]
under testing..

**Comment by amarsri28** [comment]
patch test tested with latest changes and 128 burst size. works fine

**Comment by amarsri28** [comment]
@deepaks2  pls approve

**Comment by amarsri28** [comment]
required resolution @amarsri28  working on it

**Review by deepaks2 — APPROVED** [review]

**Comment by amarsri28** [comment]
@deepaks2  few minute changes . pls review/approve.

**Review by deepaks2 — APPROVED** [review]

**Comment by amarsri28** [comment]
opening

**Comment by amarsri28** [comment]
@omecproject  can we open this pull request as its needed by cndp

**Comment by amarsri28** [comment]
@thakurajayL

**Pull request closed without merging**
