### PR TITLE
Supporting n packet burst

### PR DESCRIPTION
**Pull request by amarsri28**

### CODE REVIEW

**Comment by omecproject** [comment]
Can one of the admins verify this patch?

**Comment by amarsri28** [comment]
same as #602 as that request couldnt reopened. @deepaks2

**Review by deepaks2 — DISMISSED** [review]

**Comment by amarsri28** [comment]
restest please

**Review by deepaks2 — APPROVED** [review]

**Comment by gab-arrobo** [comment]
@amarsri28, did you check that these changes do not conflict with others? I am seeing conflicts when trying to apply patch `0017-Make-table-sizes-configurable.patch` because of the changes you made to `0012-Dpdk-concurrent-hash-support-pipeline-improvement.patch`. This is the message I get:
```
error: patch failed: core/modules/wildcard_match.cc:147
error: core/modules/wildcard_match.cc: patch does not apply
```

**Comment by amarsri28** [comment]
> @amarsri28, did you check that these changes do not conflict with others? I am seeing conflicts when trying to apply patch `0017-Make-table-sizes-configurable.patch` because of the changes you made to `0012-Dpdk-concurrent-hash-support-pipeline-improvement.patch`. This is the message I get:
> 
> ```
> error: patch failed: core/modules/wildcard_match.cc:147
> error: core/modules/wildcard_match.cc: patch does not apply
> ```

i do not get you here. branch is compiling perfectly with this change set. do you mean to say your upcoming patch(yet to be merged) has a conflict with this??

**Comment by gab-arrobo** [comment]
> > @amarsri28, did you check that these changes do not conflict with others? I am seeing conflicts when trying to apply patch `0017-Make-table-sizes-configurable.patch` because of the changes you made to `0012-Dpdk-concurrent-hash-support-pipeline-improvement.patch`. This is the message I get:
> > ```
> > error: patch failed: core/modules/wildcard_match.cc:147
> > error: core/modules/wildcard_match.cc: patch does not apply
> > ```
> 
> i do not get you here. branch is compiling perfectly with this change set. do you mean to say your upcoming patch(yet to be merged) has a conflict with this??

No, what I am saying is that I cloned BESS (https://github.com/omec-project/bess.git), then checked out `dpdk-2011-focal` branch and then manually start applying each of the BESS patches from the UPF repo (`patches/bess`)... That is, I started applying each of the patches in order ( `git apply ~/upf/patches/bess/001-xxxxxxx.patch`, then apply patch `002-xxx.patch` and so on) and when I tried to apply patch `0017-xxx.patch` I get the error I mentioned above. If I do this same process before your [PR 642](https://github.com/omec-project/upf/pull/642) was merged, I did not have any problem and I can apply all of the `bess` patches.

**Comment by amarsri28** [comment]
Thanks for sharing detail .  Could see 3 question here: 
1) does code (upf git) build successfully with this patch without throwing any error ?
2) does it work functionally (how i tested)???
3) if bess compiled successfully with in UPF then why getting this error

---> will address one by one
1) BUILD --> SUCCESSFUL, UPF code build successfully with this patch. (attached successful build logs, with other additional info),  also applied patches one by one by "git apply" command and its successful - logs attached.

2) FUNCTIONAL TESTING --> PASS,  tested by increasing burst size and it worked perfectly fine.

In usual development cycle , developers may develop and test patch under upf only
and our build system shall be strong enough to test only without the
need of runing extra commands on bess.

i didnt tried to dig more on diff between git am and git apply - but i think plain git am might be more
 restrictive for non coding convention.       can you try same command which upf is using for merging patch and its been successful.
git-apply
[successful-build-logs.txt](https://github.com/omec-project/upf/files/9900674/successful-build-logs.txt)

**Comment by amarsri28** [comment]
[LOGS.zip](https://github.com/omec-project/upf/files/9900710/LOGS.zip)

**Comment by gab-arrobo** [comment]
> Thanks for sharing detail . Could see 3 question here:
> 
> 1. does code (upf git) build successfully with this patch without throwing any error ?
> 2. does it work functionally (how i tested)???
> 3. if bess compiled successfully with in UPF then why getting this error
> 
> ---> will address one by one
> 
> 1. BUILD --> SUCCESSFUL, UPF code build successfully with this patch. (attached successful build logs, with other additional info),  also applied patches one by one by "git apply" command and its successful - logs attached.
> 2. FUNCTIONAL TESTING --> PASS,  tested by increasing burst size and it worked perfectly fine.
> 
> In usual development cycle , developers may develop and test patch under upf only and our build system shall be strong enough to test only without the need of runing extra commands on bess.
> 
> i didnt tried to dig more on diff between git am and git apply - but i think plain git am might be more restrictive for non coding convention. can you try same command which upf is using for merging patch and its been successful.

I gave it another try using a "fresh" clone of BESS and UPF and I do not see the issue/conflict I mentioned earlier. However, I still see the warning with patch 0012. It would be good you clean that up to avoid having those warnings and have a clean `git apply`. Here is what I see:
```bash
$ git apply ../upf/patches/bess/0001-Add-2-workers-support-to-Nat-module.patch
$ git apply ../upf/patches/bess/0002-Use-same-rss-key-across-interfaces.patch
$ git apply ../upf/patches/bess/0003-Add-FIB-routing-support-in-IPLookup-module.patch
$ git apply ../upf/patches/bess/0004-IOVA-mode-correction.patch
$ git apply ../upf/patches/bess/0005-Expose-PMDPort-socket-memory-allocation.patch
$ git apply ../upf/patches/bess/0006-Add-switch-for-promiscuous-mode.patch
$ git apply ../upf/patches/bess/0008-Enable-hardware-checksum-offload.patch
$ git apply ../upf/patches/bess/0009-Adding-value-attributes-to-ExactMatch-WildcardMatch.patch
$ git apply ../upf/patches/bess/0010-Add-hardware-rx-checksum-offload-option-for-checksum.patch
$ git apply ../upf/patches/bess/0011-Protobuf-update-to-new-module-messages.patch
$ git apply ../upf/patches/bess/0012-Dpdk-concurrent-hash-support-pipeline-improvement.patch
../upf/patches/bess/0012-Dpdk-concurrent-hash-support-pipeline-improvement.patch:40: trailing whitespace.

../upf/patches/bess/0012-Dpdk-concurrent-hash-support-pipeline-improvement.patch:47: trailing whitespace.

../upf/patches/bess/0012-Dpdk-concurrent-hash-support-pipeline-improvement.patch:296: trailing whitespace.
  else
warning: 3 lines add whitespace errors.
$ git apply ../upf/patches/bess/0013-Use-rte_flow_create-to-do-GTPU-RSS.patch
$ git apply ../upf/patches/bess/0014-Add-ice-iavf-to-list-of-drivers-need-SW-port-stats.patch
$ git apply ../upf/patches/bess/0015-Protobuf-changes-for-Qos.patch
$ git apply ../upf/patches/bess/0016-Newer-versions-require-go_package-stated-in-proto.patch
$ git apply ../upf/patches/bess/0017-Make-table-sizes-configurable.patch
$ git apply ../upf/patches/bess/0017-QoS-Measure.patch
$ git apply ../upf/patches/bess/0018-Increase-max-tuple-num.patch
$ git apply ../upf/patches/bess/0019-GUI-dot-module-name-quote.patch
```

**Pull request merged**
